name: cypruslockdown
description: A tool that helps you prepared the sms to get out of the house in Ctprus.

version: 1.0.5+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_sms: ^2.1.1
  shared_preferences: ^0.5.12+4
  provider: ^4.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/Greek.json
    - assets/English.json

